boards:
  - type: servo-v4
    quantity: 25
    dest_sheet: ServoBoard

generics:
  # Commented = not currently stocked by Beta
  sr-c-100n-0402-16v: SMD Capacitor, 100nF, 10%, 16V, 0402
  sr-c-100n-0603-50v: SMD Capacitor, 100nF, 10%, 50V, 0603
  sr-c-10n-0402-25v: SMD Capacitor, 10nF, 10%, 25V, 0402
  #sr-c-1n5-0402-50v: SMD Capacitor, 1.5nF, 10%, 50V, 0402
  #sr-c-1u-0402-10v: SMD Capacitor, 1uF, 10%, 10V (16V is suitable), 0402
  sr-c-1u-0603-16v: SMD Capacitor, 1uF, 10%, 16V, 0603
  #sr-c-22u-0805-10v: SMD Capacitor, 22uF, 10%, 10V, 0805
  #sr-c-22u-1210-16v: SMD Capacitor, 22uF, 10%, 16V, 1210
  #sr-c-27p-0402-50v: SMD Capacitor, 27pF, 10%, 50V, 0402
  #sr-c-470n-0603-25v: SMD Capacitor, 470nF, 10%, 25V, 0603
  #sr-c-47u-1206-6v3: SMD Capacitor, 47uF, 10%, 6.3V, 1206
  sr-r-10-0402: SMD Resistor, 10ohm, 1%, 62.5mW, 0402
  sr-r-100-0402: SMD Resistor, 100ohm, 1%, 62.5mW, 0402
  sr-r-1000k-0402: SMD Resistor, 1Mohm, 1%, 62.5mW, 0402
  sr-r-10k-0402: SMD Resistor, 10kohm, 1%, 62.5mW, 0402
  sr-r-1k-0402: SMD Resistor, 1kohm, 1%, 62.5mW, 0402
  #sr-r-2k49-0402: SMD Resistor, 2.49kohm, 1%, 62.5mW, 0402
  sr-r-330-0402: SMD Resistor, 330ohm, 1%, 62.5mW, 0402
  sr-r-390-0402: SMD Resistor, 390ohm, 1%, 62.5mW, 0402
  sr-r-4k7-0402: SMD Resistor, 4.7kohm, 1%, 62.5mW, 0402

substitutions:
  # Unusual or unqueryable distributors. Replace with same part from a different distributor.
  - replace: digikey 609-4048-6-ND
    with: farnell 2490660

  # Generic parts that are out of stock. Replace with any compatible part.
  - replace: farnell 1759381
    with: farnell 1458896
  - replace: farnell 1759467
    with: farnell 1759466
  - replace: farnell 1828809
    with: mouser 81-GRT31CR61A476KE3L

  # Specific parts that are out of stock. Replace with same part from a different distributor.
  - replace: farnell 2295989
    with: farnell 3118164

  # Obsolete parts. Replace with as close a match as possible.
  # mfr part no BSH121,135 -> BSS138BKW,115 (nexperia's suggested replacement)
  # Note that the Farnell product page for BSH121,135 is wrong and the Ids of the
  # BSH121,135 is actually 300mA; hence there is no problem in switching to a 320mA part.
  - replace: farnell 1758072
    with: farnell 2053836
  # mfr part no EDZTE615.1B -> EDZVT2R5.1B
  - replace: farnell 1679978
    with: farnell 2536475

  # Cheaper alternatives
  - replace: farnell 1867956
    with: farnell 2611932
